export const REGISTER_SHEET_REQUEST = "REGISTER_SHEET_REQUEST";
export const REGISTER_SHEET_SUCCESS = "REGISTER_SHEET_SUCCESS";
export const REGISTER_SHEET_FAIL = "REGISTER_SHEET_FAIL";

export const GET_SHEET_REQUEST = "GET_SHEET_REQUEST";
export const GET_SHEET_SUCCESS = "GET_SHEET_SUCCESS";
export const GET_SHEET_FAIL = "GET_SHEET_FAIL";

export const DELETE_ROW_REQUEST = "DELETE_ROW_REQUEST";
export const DELETE_ROW_SUCCESS = "DELETE_ROW_SUCCESS";
export const DELETE_ROW_FAIL = "DELETE_ROW_FAIL";